server:
  port: 8080
  mode: debug  # debug, release, test
  log_level: debug
  allow_origin: "*"

database:
  driver: mysql
  host: localhost
  port: 3306
  user: root
  password: 123456
  name: lengdong
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "lnx1Auv6z4eJRs87WYnplyK3qOhmTDEP"
  expire_time: 24  # in hours

blockchain:
  network_config_path: "./blockchain/network/config.yaml"
  channel_id: "coldchain-channel"
  chaincode_name: "coldchain-cc"
  org_admin: "Admin"
  org_name: "Org1MSP"
ethereum:
  node_url: "http://127.0.0.1:8545/"
  contract_address: "0x5FbDB2315678afecb367f032d93F642f64180aa3" #冷冻品合约部署地址
  private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" 