version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: coldchain_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: coldchain_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coldchain_network

  redis:
    image: redis:6.0
    container_name: coldchain_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - coldchain_network

  user-service:
    build:
      context: .
      dockerfile: ./docker/user-service/Dockerfile
    container_name: coldchain_user_service
    restart: always
    ports:
      - "8081:8080"
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - mysql
      - redis
    networks:
      - coldchain_network

  factory-service:
    build:
      context: .
      dockerfile: ./docker/factory-service/Dockerfile
    container_name: coldchain_factory_service
    restart: always
    ports:
      - "8082:8080"
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - mysql
      - redis
      - blockchain-service
    networks:
      - coldchain_network

  query-service:
    build:
      context: .
      dockerfile: ./docker/query-service/Dockerfile
    container_name: coldchain_query_service
    restart: always
    ports:
      - "8083:8080"
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - mysql
      - redis
      - blockchain-service
    networks:
      - coldchain_network

  blockchain-service:
    build:
      context: .
      dockerfile: ./docker/blockchain-service/Dockerfile
    container_name: coldchain_blockchain_service
    restart: always
    ports:
      - "8084:8080"
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./blockchain:/app/blockchain
    depends_on:
      - mysql
      - redis
    networks:
      - coldchain_network

  admin-service:
    build:
      context: .
      dockerfile: ./docker/admin-service/Dockerfile
    container_name: coldchain_admin_service
    restart: always
    ports:
      - "8085:8080"
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - mysql
      - redis
    networks:
      - coldchain_network

networks:
  coldchain_network:
    driver: bridge

volumes:
  mysql_data:
